// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5EMbQtzqr0wmyl8IY5vXA-U7d5QZcoxU',
    appId: '1:896506010574:web:757e86c3026fa63535a99f',
    messagingSenderId: '896506010574',
    projectId: 'whatsappclone-8a9cc',
    authDomain: 'whatsappclone-8a9cc.firebaseapp.com',
    storageBucket: 'whatsappclone-8a9cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpnpVcu-HTj3S_jpR3U1ZiKux6WpBjac',
    appId: '1:896506010574:android:de71f51e606230fa35a99f',
    messagingSenderId: '896506010574',
    projectId: 'whatsappclone-8a9cc',
    storageBucket: 'whatsappclone-8a9cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAym-Xw1GjL3wm0uT9MfXC35JWkpMCbrs0',
    appId: '1:896506010574:ios:a130dccb685697ca35a99f',
    messagingSenderId: '896506010574',
    projectId: 'whatsappclone-8a9cc',
    storageBucket: 'whatsappclone-8a9cc.appspot.com',
    iosClientId: '896506010574-fo6ufsjko8iblq41h9gpqj2169gff9tt.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAym-Xw1GjL3wm0uT9MfXC35JWkpMCbrs0',
    appId: '1:896506010574:ios:a130dccb685697ca35a99f',
    messagingSenderId: '896506010574',
    projectId: 'whatsappclone-8a9cc',
    storageBucket: 'whatsappclone-8a9cc.appspot.com',
    iosClientId: '896506010574-fo6ufsjko8iblq41h9gpqj2169gff9tt.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppclone',
  );
}
